### ISSUE TITLE
Unable to load a saved game.

### ISSUE THREAD

**Issue by En-TACT** [janxious/ModTek#11]
I installed the latest BTML (v0.7.0), ModTek (v0.4.2), and, the Archer and Rifleman (for MechEngineer) mods after playing BattleTech for 1072 days in the game.   I executed BattleTechModLoaderInjector and it successfully created a new Assembly-CSharp.dll and backed-up the original file.  When I attempt to return to my campaign (or load a saved file) it idles on loading; like in a loop with the black screen and animation rotating in the top left corner.  However, if I delete Assembly-CSharp.dll created by BattleTechModLoaderInjector and, return to the original Assembly-CSharp.dll the game loads saved files.  I'm on Windows 10 64-bit and my BattleTech version show 1.3.2-418R W/MODTEK V0.4.0.19688.

**Comment by CptMoore** [comment]
try to add btml and modtek log files to this issue

BTModLoader.log
ModTek.log

**Comment by En-TACT** [comment]
[ModTek.log](https://github.com/janxious/ModTek/files/2716294/ModTek.log)
[BTModLoader.log](https://github.com/janxious/ModTek/files/2716293/BTModLoader.log)

**Comment by CptMoore** [comment]
attach output_log.txt too please

I'm no expert on debugging these things

**Comment by En-TACT** [comment]
This "output_log" is from C:\Program Files (x86)\Steam\steamapps\common\BATTLETECH\BattleTech_Data
[output_log.txt](https://github.com/janxious/ModTek/files/2716347/output_log.txt)

**Comment by CptMoore** [comment]
ok, doesnt look I can help you, nothing out of the ordinary, try joining https://discord.gg/zRptMZD there is a lively community with more knowledge on how to solve these things

**Comment by janxious** [comment]
I ho9pe you have solved your problem. If not, please re-file an issue at https://github.com/BattletechModders/ModTek/issues
