### ISSUE TITLE
Texture2D/Sprite lookup issues

### ISSUE THREAD

**Issue by m22spencer** [janxious/ModTek#13]
We keep running into issues around sprites & textures, and the issue is likely here:
https://github.com/janxious/ModTek/blob/master/ModTek/Patches.cs#L164

Battletech relies on id collision for textures & sprites.  In case of recieiving a texture when asking for a sprite the game will create a new sprite on the fly.

The temporary fix would be to extend this patch to check types as well.

**Comment by mpstark** [comment]
Would #14 fix this as well, since that no longer patches `BattleTechResourceLocator.EntryByID`?

**Comment by m22spencer** [comment]
Yes

**Comment by mpstark** [comment]
This seems to have been caused by `DataManager_Texture2DLoadRequest_OnLoaded_Patch`

As it isn't clear that this patch is in use by anyone, I've gotten rid of it on the BTRL branch, as discussed in Discord.

**Comment by janxious** [comment]
I believe this is solved in mainline MT: https://github.com/BattletechModders/ModTek/
