### ISSUE TITLE
modtek does not always load mods with 5.0

### ISSUE THREAD

**Issue by unclecid** [janxious/ModTek#19]
since updating to 5.0 anytime i make changes to mods folder be it adding or removing mods or editing a json file modtek will not load mods next time i launch battletech.
it also seems that even when i do not mess with anything this can still happen so i am not exactly sure of cause.
i have tried completely reinstalling everything including btml/modtek but this still happens.
deleting modtek folder and relaunching fixes it at that time.
the progress bar will go immediately to game now loading message and then to hbs logo 
when this happens a check of modtek.log shows empty other then timestamp.

asked on paradox forums and no one else seems to have this issue.
is it possible this is happening because i am running ALOT of mods all at once? (53+ mods)

**Comment by janxious** [comment]
This fork is no longer maintained as stated in the README. Check https://github.com/BattletechModders/ModTek. 

If you file a ticket there, we will need to see btmodloader.log and modtek.log to find out.
