### ISSUE TITLE
Modtek not working with BTG 1.3.

### ISSUE THREAD

**Issue by jaydys** [janxious/ModTek#6]
I have installed ModTek v0.4.2 and BTML 6.4.2.  I followed the instructions like I always do.
When I startup the game using either steam or the BT Launcher, I get a black screen with a box in the middle that has ModTek 0.4.0.xxxxx on it and it goes nowhere else.  The injector seems to complete without any errors.
I removed the files after unloading BTML and then tried to install it again.  And again I get the same screen.
Without ModTek and BTML installed the game runs normally.
![modtekerror](https://user-images.githubusercontent.com/45528006/49336151-10da4280-f5c2-11e8-8dd8-55e1a631f29d.jpg)

**Comment by janxious** [comment]
Can you drop me various logs from your game? I will need unity's output.log, modtek.log, and btml.log.

**Comment by LadyAlekto** [comment]
Similar reports of this had been fixed by deleting the .modtek folder (aka remove old cache)

**Comment by jaydys** [comment]
I believe I tried that once LadyAlekto.  But I will happily try it again and if it does not work I will provide the log files for you Janxious.
I will say that I loaded up 0.4.0 and it loads the game, but the mods don't seem to work.

**Comment by jaydys** [comment]
Ok.  Cleared out all the mod folder and put the 0.4.2 files back in.  Started up this time.
Still having issues with some of the mod changes, but that is something I can figure out.
Thanks guys.
