### ISSUE TITLE
ModTek manifest overrides.

### ISSUE THREAD

**Issue by m22spencer** [janxious/ModTek#8]
First, just a bit of an overview:

There are two "manifests" to BattleTech. 
- The `VersionManifest` (addendums, memory stores, etc..)
- The `BattleTechResourceLocator` (Dictionary of type -> id -> VersionManifestEntries[])

The VersionManifest is an abstraction that sits behind the BattleTechResourceLocator.

# VersionManifest
First, here's a summary of what occurs on a mostly vanilla (Non flashpoint!) startup in 1.3:
Mods : { BTML, ModTek, BattleTechPerformanceFix, FuckyYouLogShit, SkirmishEquipmentUnloc, SkipIntro }
```
ConversationTextureAddendum -> AddAddendum
BackerEmblems               -> AddAddendum
MechLabTutorial             -> AddAddendum
MechLabSkirmishTutorial     -> AddAddendum
PlayerEmblems               -> AddAddendum

ModTek Initialize

BattleTechResourceLocator::RefreshTypedEntries

ModTek:CustomUnits          -> AddAddendum
ModTek:CustomUnits          -> AddAddendum
ModTek:CustomUnits          -> AddAddendum

BattleTechResourceLocator::RefreshTypedEntries

flashPointManifest          -> AddAddendum

BattleTechResourceLocator::RefreshTypedEntries

CustomUnits                 -> AddAddendum
CustomUnits                 -> AddAddendum
CustomUnits                 -> AddAddendum

BattleTechResourceLocator::RefreshTypedEntries

flashpoint                  -> AddAddendum
flashpoint                  -> ApplyAddendum 

BattleTechResourceLocator::RefreshTypedEntries

MainMenu
```

Seen above, flashpoint load occurs later than modtek, and ends up overwriting the modtek addendums.

# BattleTechResourceLocator
This class does have some public facing addendum/memory store methods, but as far as I can tell, all entry lookups are done through the following methods:
```csharp
VersionManifestEntry EntryByID(...)
VersionManifestEntry[] AllEntriesOfResource(...)
VersionManifestEntry[] AllEntriesOfResourceFromAddendum(...)
```

Note that there is another method `AllEntries`, but this method *only* returns the base manifest for the base game and should not be used.

Each of the above calls checks if the manifest has been modified via addendums, and if so calls `RefreshTypedEntries` which rebuilds the BTRL manifest.

At the core, BTRL is nothing but three dictionaries `Dictionary<string, Dictionary<BattleTechResourceType, VersionManifestEntry>>`.
 - One for base game `baseManifest`
 - One for content packs `contentPacksManifest`
 - One for addendum specific lookups `addendumsManifest`

# Observations
Currently, ModTek works with addendums, and the more internal `VersionManifest` type. This makes it subject to being overwritten by addendums added post ModTek init.
This also means ModTek would never be able to override things fetched specifically from a single Addendum `CONVERSATION_TEXTURE_ADDENDUM` & `PLAYER_CREST_ADDENDUM`.

# Proposal
- Modify ModTek to build nothing but a `VersionManifest[]` list, containing the entries it wants overridden.
- Patch the `RefreshTypedEntries` method with a Post patch, which will add the ModTek overrides directly to the BTRL `baseManifest`, `contentPacksManifest`, and `addendumsManifest`

Your thoughts?

**Comment by CptMoore** [comment]
Sounds necessary. Having an extra VersionManifest[] makes sense, keeps the datastructure as near as the original code but still separate.

But also should help with separation of concerns for more features in the future, e.g. if we cache that manifest and we get rid of absolute paths in the other cache files, one could provide already modtek cached/compiled mod packs. That should speed up the brutally long initial loading time of roguetech.

**Comment by m22spencer** [comment]
Optimally, I'd like to modify the entire manifest to be nothing but a single dictionary lookup of `id -> VersionManifestEntry`,  as the nested dictionaries are extremely slow to search.

Seems preferable to have a single flat dictionary to pull from, and then do all the content checks/overrides once only during the `RefreshTypedEntries` phase.

This change, being significant will require some hefty review though, as we don't want to break the DLC ownership checks in any way.

**Comment by janxious** [comment]
> as the nested dictionaries are extremely slow to search

Also: the memory!

----

On the face of it, this seems like a necessary change given how flashpoint (and presumably future DLC) is built. My most desired implementation of this has an a/b switch for which system of manifest use we try to use so it's easy to find out if it's working the same, but that has some implementation downsides and probably requires some instrumentation for the end product which may not exist currently.

Anyway, if you want me to dig into the problem further let me know. Otherwise I assume you have the stick @m22spencer

**Comment by mpstark** [comment]
Just to be clear, I don't think that this changes much of the internal workings of ModTek. There are some organizational things that we could tinker with, but the outcomes of this would be that ModTek:

* Doesn't patch `BattleTechResourceLocator.EntryByID`
* No longer actually caches or modifies the manifest/addendums
* Maintains a list of `VersionManifestEntry` (probably just expose/modify `List<ModDef.ManifestEntry> modEntries`, which is already maintained and is easily transformed into `VersionManifestEntry`)
* Patch `BattleTechResourceLocator.RefreshTypedEntries`
   * Takes `modEntries` and sorts into buckets of `baseManifest`, `contentPacksManifest`, and `addendumsManifest`

Additionally, we should probably introduce a new member for the ModTek internal `IManifestEntry` that specifies an official content pack that it relies on. There's some additional handling that we should do for DLC regarding merging JSON into it, I'll open another issue for that.

Did I cover the bases?

**Comment by mpstark** [comment]
Should I start work on this or did you have a WIP?

**Comment by m22spencer** [comment]
No WIP, this is pretty low on my priority list.  If you'd like to take it that'd be great.

Edit:
At some point bfix will patch the RefreshTypedEntries function, as it's a major performance bottleneck.  I'll coordinate with you when I start work on this.

**Comment by mpstark** [comment]
Worked on it, got something that I think is working, though obviously limited testing.

https://github.com/Mpstark/ModTek/tree/Feature/DirectToBTRL

Precompiled here: [ModTek.zip](https://github.com/janxious/ModTek/files/2718988/ModTek.zip)

**Comment by m22spencer** [comment]
Consider moving `var versionManifestEntry = entry.GenerateVMEntry();`, outside of the RefreshTypedEntries.  This method gets called a lot, best to not pay this cost several times per load screen.

**Comment by mpstark** [comment]
I've cached it internally to the entry. There are log messages currently that will slow things down obviously. I don't own Flashpoint currently, so I can't really test the DLC stuff. I also don't have a test case for addendums either.

[ModTek.zip](https://github.com/janxious/ModTek/files/2719035/ModTek.zip)

I'll open a pull request so we can discuss it better there.

**Comment by mpstark** [comment]
Because of some git misadventures, I had to make another branch:

https://github.com/Mpstark/ModTek/tree/Feature/DirectToBTRL2

**Comment by janxious** [comment]
This is now a part of mainline MT.
